---
title: "Pythagorean Expectation Across Various Sports"
author: "David Teuscher"
date: '2022-07-30'
slug: pythagorean-model-in-sports
categories: []
tags: []
subtitle: ''
summary: 'This is the post summary'
authors: []
lastmod: '2022-07-30T19:13:34-06:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
# Overview of Pythagorean Expectation
```{r}
library(Lahman)
library(tidyverse)
```

# Pythagorean Exponent For Different Sports
## MLB
```{r}
mlb <- Teams %>% 
    filter(yearID > 1900) %>%
    select(teamID, yearID, lgID, G, W, L, R, RA) %>%
    mutate(RD = R - RA, 
           Wpct = W / (W + L))

mlb_pyt <- mlb %>%
    mutate(log_w_ratio = log(W/L),
           log_r_ratio = log(R / RA))
pyt_fit <- lm(log_w_ratio ~ -1 + log_r_ratio, data = mlb_pyt)
coef(pyt_fit)

```

## NHL
```{r}
library(nhlapi)

nhl <- nhl_standings(seasons = 1990:2022)
nhl_data <- nhl$teamRecords %>%
    bind_rows() %>%
    mutate(point_diff = goalsScored - goalsAgainst,
           Win_pct = leagueRecord.wins/leagueRecord.losses,
           log_win_ratio = log(leagueRecord.wins/leagueRecord.losses),
           log_point_ratio = log(goalsScored/goalsAgainst))
pyt_fit_nhl <- lm(log_win_ratio ~ -1 + log_point_ratio, data = nhl_data)
coef(pyt_fit_nhl)
```

## NFL
```{r, message=FALSE}

library(espnscrapeR)
library(purrr)
season <- espnscrapeR::get_nfl_standings(season = 2002)

nfl_data <- map_df(2002:2021, get_nfl_standings)

nfl_pyt <- nfl_data %>%
    mutate(log_w_ratio = log1p(wins) - log1p(losses),
           log_point_ratio = log(pts_for/pts_against))
pyt_fit <- lm(log_w_ratio ~ -1 + log_point_ratio, data = nfl_pyt)
coef(pyt_fit)


```

## NBA
```{r}
library(hoopR)
nba_data <- map_df(1994:2021, espn_nba_standings)
nba_data <- nba_data %>%
    mutate(wins = as.numeric(wins),
           losses = as.numeric(losses),
           avgpointsfor = as.numeric(avgpointsfor),
           avgpointsagainst = as.numeric(avgpointsagainst),
           games = wins + losses,
           points_for = games*avgpointsfor,
           points_against = games*avgpointsagainst,
           point_diff = points_for - points_against,
           log_w_ratio = log(wins/losses),
           log_point_ratio = log(points_for/points_against))
pyt_fit_nba <- lm(log_w_ratio ~ -1 + log_point_ratio, data = nba_data)
coef(pyt_fit_nba)
```

# Summary